language: python
python:
- 3.6.1
install: pip install -r requirements.txt
script:
  - python flask_tests.py
deploy: &heroku
  provider: heroku
  api_key: "IFuwy1XL72/c8O6nQQiJxUPzguNkdaNnZXjh7Tc5KwIkjvXysKgbV5FP/lSnzYZxuRX6VCYLDX/b00vgXUNGfm2+xYv4aPagQxnlmpEehmzXY3YiP2tQp0FNq1CY06/TDg/RuzisSCtCcBbln8o66R9vUUR16JNFEWuqGbRnWnLAoBgmYQvA7ZY19ledSG82bMy2qbDdh4ixuv5QtWaBVUvU4B+DDywSOwUIJRWZGqFDeJXQb89FgGEC97utEssrn62YLz04hm0qCo2iAQL6Vcf3dite9MNeGRRl3yvSpEWlK02Dbm1WLwPMpyLcu0yzt3ePgS1lFtaExJv8/s3Ap57rEDjLZiV2A5rhTqckHMZl074Jjb1Iw/jQZaYzBXe8DrRk3+TIfzEHSCqX+GzDhrbQsMfvg6BRagQXGDFDk7c0YezQM0BA0tn96BBx3OiABRVrdIE88OeZPfhYniOUIK7uD8E/dcu6KwTu8PBTd0eOvsmUujhNksOT+zs6v4V4zTRM06Clxs6pNPyfaeV1vSnLvCm+93s9MO+3timGPZGC4T0g1I4Ut9kIV4j+PJv06qg7wroU6MDe2O8T0wToVRNPaIiR6gA8BlxFr8Clp9/Mko8mQ7wjH+KdWDNqg7uogU4sGtEBNxK7qNyAmYNgRsNP7FiKKmYKmDKdikUQYdM="
  app: vtipystarejmatere
  on:
    repo: filipmihal/WebJokeApp
