language: python
python:
- 3.6.1
install: pip install -r requirements.txt
script:
- python flask_tests.py
deploy:
  provider: heroku
  api_key:
    secure: Css5Tti7RiCvWe7JEVyP8rBG4fRVUXC27pAlPcM4E1lX4NNOTIGOgmevzOkcx51C4kFtdsFbiAdxUd2qQ7iE5p6TKQ3Zh3Jet4wicLy/MHlZUfEeiLREGTY86OjiMt/sHt4f2/UUxsotwAJEUvYm2bZ74LmKKrlILGN0fT/3mHAnnuZI/wbr1J48dToFx6x1dcvTrgHsPUFx93BaX6DM1rwrbJ6/4mH+DMbxgKeTKOdNjIj1msURezGXLhgbvEgf1hZ8sbF2UYcD/+i9zXJcg602IE/pFZKISGm3aCbpb0fXd+VtQEWsJOZNIaA2kWv00vw9XMNHZE/JOzSgtxyQu7pubbNd+GkdDJ76EKF8jwPsifC/VTWYHe2mAkAE2FYHfi2I0SZOCSO3vh8TfhkBsKxm1klVCTxANWqUP7L5POmt5QJLMB3ZDGpBr18SyTDYrMHIT4gzRNduVgSEiKOR9SktV7cUV4HnTx5Mjvw765skWpi5u7jwvQHDB1yjTnw5HzQBC5KCHqzrc13lxdfEu1PZbO7lCJLwr6ASnAYFzUR3ReL9kxstGPNcYJHl21ZdN/qaIm2HWLtxVpENzbzi2P0ZG2EoDo0BS7GgIEWgxmT9W3Q7qBFVT4GOYncJfiV7RSeGljpPAdjPvgIDiiJxSjqP05c/OJEQ116GE/Hrkzc=
  app: vtipystarejmatere
  on:
    repo: filipmihal/WebJokeApp
