language: python
python:
- 3.6.1
install: pip install -r requirements.txt
script:
- python flask_tests.py
deploy:
  provider: heroku
  api_key: 0ab4c165-fba0-44ca-af33-66d6144c2cba
  app: vtipystarejmatere
  on:
    repo: filipmihal/WebJokeApp
