language: python
python:
- 3.6.1
install: pip install -r requirements.txt
script:
- python flask_tests.py
deploy:
  provider: heroku
  api_key:
    secure: MF2gUp3km72lSrOdM+q1ztM7B98u+hiB+P2+wG7cUIrocAx6uWy7VVa7LZuRg9cDZZZoko4lVsZ+E3L6wdSnAosu35LgEUKeT9//MrWtscSsBEupFEOeaoLqnRd0XqF5Se3ef8bTeM6sgO8amDHYTFLtEqUVD+APJP0EKQyyQPxCLDxGnDJBsrNR50QcbtG9uMuD+6i+tcUYl4h9RybcI+UPCM/dphk196ATJGZVZV6x/i2ciTJK1N3jVzm2MgiRlESAZeGqxUJkMJzkLu9VJibnMyxd/cesqW8uRzxSibCF2UYSTcdKhlgr377R6NrTYXqK5AiIKft6tCuqe7U5mujNgd88c7sf6eoDCrFoRgplP2ULmkTEKnSVYRC3slC1hoLeozYZE+C+pJVYIa4Pyy8kwZs+1sA5Z1HwnIqDqG0nupWe1SLWdvF3Ou79/HuhVDuyEgBfAnIF0qVMbok6ej8Qhz8JWA+DneYjpH4MHd7TyHVegb1DwSlIgOMZBhreGxfVcB4yXSgcYYgiof9NE4xzGXt9ClSr11AvDu1Oli1SEPtRUmQ5HrjYigiB+xrEeEb7VugntqhxtUA/4CXyrfTR8lnc7KQmqLwpf5zbMUa1EfoPINIyuFDl01CMSf38kYkmG7k0gq9U1Vj41asIhvNNNqBpCnpk/g6lS8joBnI=
  app: vtipystarejmetere